DROP TABLE COMPTE CASCADE CONSTRAINT PURGE;

CREATE TABLE COMPTE ( ID INT, LIBELLE VARCHAR(15), SOLDE NUMBER(10,2));

INSERT INTO COMPTE (Id, Libelle, Solde) VALUES (1,'CC', 2500);
INSERT INTO COMPTE (Id, Libelle, Solde) VALUES (2,'LIVRETA', 3400);
INSERT INTO COMPTE (Id, Libelle, Solde) VALUES (3,'LIVRETJ', 1800);
INSERT INTO COMPTE (Id, Libelle, Solde) VALUES (4,'LIVRETD', 1950);
INSERT INTO COMPTE (Id, Libelle, Solde) VALUES (5,'PEL', 10000);
COMMIT;