DROP TABLE PERSONNEL CASCADE CONSTRAINT PURGE;

CREATE TABLE PERSONNEL ( ID INT, LIBELLE VARCHAR(15), SALAIRE NUMBER(10,2));

INSERT INTO PERSONNEL (Id, Libelle, SALAIRE) VALUES (1,'TRAD', 2500);
INSERT INTO PERSONNEL (Id, Libelle, SALAIRE) VALUES (2,'UYER', 3400);
INSERT INTO PERSONNEL (Id, Libelle, SALAIRE) VALUES (3,'BARTOL', 1800);
INSERT INTO PERSONNEL (Id, Libelle, SALAIRE) VALUES (4,'CREDUI', 1950);
INSERT INTO PERSONNEL (Id, Libelle, SALAIRE) VALUES (5,'XAPLET', 10000);
COMMIT;